name: "Universal Airport Check-in" # Combined name for the entire workflow

on:
  schedule:
    - cron: "0 14 * * *"  # Triggers daily at 06:00 (UTC+8) - From original workflow 1
    - cron: "10 22 * * *"  # Triggers daily at 06:10 (UTC+8) - From original workflow 2
  workflow_dispatch: # Manual trigger from both original workflows

env:
  RUN_ENV: 'prod' # Common environment variable

jobs:
  checkin_1: # Represents the job from the first original workflow (Job ID)
    name: "Check-in 1 (Python 3.10)" # More descriptive name in GitHub Actions UI
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master' # Uncomment if needed

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up Python 3.10
        uses: actions/setup-python@v5 # Use v5 action from the first original workflow
        with:
          python-version: 3.10.16 # Version specified in the first original workflow

      - name: Random wait
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run check-in script 1
        env:
          URL: ${{ secrets.URL }} # Specific secrets used in the first original workflow
          SCKEY: ${{ secrets.SCKEY }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          python3 ./main.py

  checkin_2: # Represents the job from the second original workflow (Job ID)
    name: "Check-in 2 (Python 3.10)" # Updated Job name to reflect Python version
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master' # Uncomment if needed

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up Python 3.10 # Updated Step Name
        uses: actions/setup-python@v5 # **Modification: Update to v5 action**
        with:
          python-version: 3.10.16 # **Modification: Change to Python 3.10.16**

      - name: Random wait
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run check-in script 2
        env:
          URL: ${{ secrets.URL_G }} # Specific secrets used in the second original workflow
          SCKEY: ${{ secrets.SCKEY }}
          EMAIL: ${{ secrets.EMAIL_G }}
          PASSWD: ${{ secrets.PASSWD_G }}
          CONFIG: ${{ secrets.CONFIG_G }}
        run: |
          python3 ./main.py
